### ISSUE TITLE
unknown devices number

### ISSUE THREAD

**Issue by aristosv** [elad-bar/ha-edgeos#1]
Home assistant shows 15 unknown devices
![3](https://user-images.githubusercontent.com/528302/56633184-c5eec380-6665-11e9-9c84-678f56e31bfa.png)
Whereas EdgerouterX shows only 1 unknown device.
![2](https://user-images.githubusercontent.com/528302/56633190-cb4c0e00-6665-11e9-8a68-5e3f3cc05fb0.png)
Or I'm I understanding this incorrectly?

**Comment by elad-bar** [comment]
the way I implemented the component is based on the assumption that IP that is not reserved is unknown,
I'll try to check if I can change it to present just dhcp leases

**Comment by aristosv** [comment]
That's strange though, because I have nearly 80 IP addresses at home, and only 23 of them are reserved on the EdgerouterX. All the others are static IP addresses configured on the devices.

So the component should see the rest of 57 IP Addresses as unknown. But it only sees 5.

**Comment by JunShine** [comment]
that.....I can't find any devices in my router.Is that so?

**Comment by elad-bar** [comment]
should be solved, can you check?

thanks

**Comment by aristosv** [comment]
I have since moved to a unifi system, so I dont have the router any more
