### ISSUE TITLE
Cannot connect after router reboot

### ISSUE THREAD

**Issue by ocalvo** [elad-bar/ha-edgeos#10]
When the router is rebooted while HASS in running the log will start filling with this error almost every minute:
```
Failed to get devices data, Error: 403, message='Forbidden', url='https://192.168.1.1/api/edge/get.json, Line: 80
```

**Comment by elad-bar** [comment]
Applied new fix for it, tested it and it seems to be working perfect, 
Also added new binary sensor for status.

Please check.

**Comment by ocalvo** [comment]
Thanks, I have updated my Hass and my router will reboot next Sunday, I will report back if I see something in the log or not.

**Comment by elad-bar** [comment]
> Thanks, I have updated my Hass and my router will reboot next Sunday, I will report back if I see something in the log or not.

Did it work?

Thanks

**Comment by ocalvo** [comment]
Yep, I was able to see a recovery message.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
