### ISSUE TITLE
Button to reboot EdgeOS-Device?

### ISSUE THREAD

**Issue by ruegr** [elad-bar/ha-edgeos#102]
Hi,
Is it possible to add a reboot-button for an EdgeOS-device to this great integration?

Due to a lack of internet stability i need to reboot DSL-modem quite often and sometimes even the EdgeRouter-X :-|

**Comment by Dude4Linux** [comment]
+1 I'd like to have the actions `shutdown` and `reboot` added to the integration so that they can be scripted in HA.

**Comment by elad-bar** [comment]
closing as it will not be supported,
if you would like to propuse a PR for that, would be happy to see how you have addressed it including the reconnect part once internet got connected again

thanks
