### ISSUE TITLE
Unnecessary logging of the last activity attribute

### ISSUE THREAD

**Issue by freddieleeman** [elad-bar/ha-edgeos#104]
My backup took forever to complete, and when I checked, I was shocked to see that my HA database file had bloated to a whopping 20GB. The culprit was none other than the EdgeOS device tracker hogging up space in the state_attributes table. This plugin keeps updating the "Last Activity" attribute of every single device every second!

![ubnt](https://github.com/elad-bar/ha-edgeos/assets/6225998/50e335f0-a2d7-42c5-8a93-2d0b58cb537c)

**Comment by mabahj** [comment]
I think I just noticed the same. I ran an SQL query to check my database (from here: https://community.home-assistant.io/t/how-to-keep-your-recorder-database-size-under-control/295795/125 ) and the one device I'm tracking consumed 23% of all the "states" entries in the entire database. Next in line was sensor.ubnt_last_restart, which consumed 9%.

(For the record: Love the plugin, it is a really nice feature you've provided, elad-bar! Thank you, very much appreciated!)
