### ISSUE TITLE
No statistics found - UBNT Interface ETH4 Received Rate

### ISSUE THREAD

**Issue by Greminn** [elad-bar/ha-edgeos#106]
Hi There, for some reason there is no statistics graph for any port's received rate. Using a EdgeRouter X. Any chance I have something setup wrong at my end? Would love to have a dashboard graph :)

<img width="555" alt="image" src="https://github.com/elad-bar/ha-edgeos/assets/81659316/700732a0-66ed-456f-a140-34d57c6d4880">

**Comment by elad-bar** [comment]
Which version is installed (of integration and HA)? Do you see error in logs related to component?

Thanks

**Comment by Greminn** [comment]
Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

HACS EdgeOS version 2.0.28

No errors... (with debug not on)

**Comment by elad-bar** [comment]
Can you pls check if there is an issue with the entity statistics? (in developer tools -> statistics) not sure why it happens, check with my integration and it's working, my logs are also clean, for other integrations i guess it work, right?

**Comment by Greminn** [comment]
@elad-bar I think something was wrong with my config. I deleted and re-added and it's all working as excepted.
