### ISSUE TITLE
iPhone ARP disconnects and connects every few minutes

### ISSUE THREAD

**Issue by sebastian-ruiz** [elad-bar/ha-edgeos#11]
Sorry about not getting back about issue #8. My iPhone will now show switch between disconnected and connected every few minutes. This can be seen in the picture below:

<img width="349" alt="Screenshot 2019-11-26 at 11 44 01" src="https://user-images.githubusercontent.com/2012398/69623250-ceb3d780-1042-11ea-8c92-0420d5593f35.png">

My laptop and desktop do not have the same problem. Could it be that the iPhone is somehow closing the connection or something to save battery? Thank you.

**Comment by elad-bar** [comment]
It checks the last time the device sent data to the router, if it doesn't (might be safe battery mode) it will identify the device is disconnected, 
Can you share for how long it takes the device to get disconnected and then connected again? maybe I can set the threshold to be configurable per device or something like that

**Comment by sebastian-ruiz** [comment]
In Grafana I look at the data more closely (see below) for a period where my phone was home and connected to the wifi: 

<img width="1188" alt="Screenshot 2019-11-26 at 22 05 10" src="https://user-images.githubusercontent.com/2012398/69672655-d736fd00-1098-11ea-9fad-f526cc065965.png">

It looks like the largest gap is just over half an hour. This makes it not so good an indicator for when I am home. I think I will have to look for a different approach than relying on ARP to get accurate timings.

**Comment by elad-bar** [comment]
can you please check if latest version solved that issue?

thanks
