### ISSUE TITLE
How to ADD VLAN's ? For example ethX.X ?

### ISSUE THREAD

**Issue by KapriQ** [elad-bar/ha-edgeos#110]
Hello, at first, so much thanks, for such a great "module" into HAS,

I would like to monitor traffic flow on my  ETH VIF interface, how can i add it into that plugin please?

-  I have enabled DEBUG MODE 
-  but i haven't find debug file under /.../homeassistant/.storage/...  (Only 3x files ending with ...config)

Thanks :).

**Comment by elad-bar** [comment]
Is it still relevant?

**Comment by elad-bar** [comment]
Fixed in v2.1.x
