### ISSUE TITLE
Warning message that SOURCE_TYPE_ROUTER is being depriciated

### ISSUE THREAD

**Issue by GCV-Sleeper-Service** [elad-bar/ha-edgeos#122]
Logger: homeassistant.components.device_tracker
Source: helpers/deprecation.py:205
Integration: Device tracker ([documentation](https://www.home-assistant.io/integrations/device_tracker), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+device_tracker%22))
First occurred: 10:20:28 PM (2 occurrences)
Last logged: 10:20:28 PM

SOURCE_TYPE_ROUTER was used from edgeos, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.ROUTER instead, please create a bug report at https://github.com/elad-bar/ha-edgeos/issues

**Comment by redstar2k1** [comment]
Logger: homeassistant.components.device_tracker
Source: helpers/deprecation.py:205
Integration: Device tracker ([documentation](https://www.home-assistant.io/integrations/device_tracker), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+device_tracker%22))
First occurred: 20:04:36 (2 occurrences)
Last logged: 20:04:36

SOURCE_TYPE_ROUTER was used from edgeos, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.ROUTER instead, please create a bug report at https://github.com/elad-bar/ha-edgeos/issues

**Comment by elad-bar** [comment]
released [v2.1.0](https://github.com/elad-bar/ha-edgeos/releases/tag/v2.1.0), pls check and report
