### ISSUE TITLE
The method for providing platform translations has changed in Home Assistant Core

### ISSUE THREAD

**Issue by emontnemery** [elad-bar/ha-edgeos#124]
The method for providing platform translations has changed in Home Assistant Core, and this integration needs to be updated.

Details can be found in https://developers.home-assistant.io/blog/2024/03/05/platform_entity_translations_deprecation

**Comment by elad-bar** [comment]
released [v2.1.0](https://github.com/elad-bar/ha-edgeos/releases/tag/v2.1.0), pls check and report

**Comment by elad-bar** [comment]
Fixed in v2.1.x
