### ISSUE TITLE
Entities not showing with HA 2024.5.0

### ISSUE THREAD

**Issue by Testmangh** [elad-bar/ha-edgeos#131]
Everything was working normally but after updating to 2024.5.0 te integration stopped exposing entities. 
![image](https://github.com/elad-bar/ha-edgeos/assets/25848686/60e97e1a-102b-4657-b50f-a92b28b5e9cb)
<img width="728" alt="image" src="https://github.com/elad-bar/ha-edgeos/assets/25848686/b3b5aa41-c652-4df9-a62f-bd1b1a5c5d9a">

**Comment by elad-bar** [comment]
Dup #130
