### ISSUE TITLE
Convert B/s to mbit no longer available 

### ISSUE THREAD

**Issue by GnFlala** [elad-bar/ha-edgeos#133]
What the topic says.

Latest update

**Comment by elad-bar** [comment]
HA support that functionality out of the box

**Comment by GnFlala** [comment]
I cannot see it. Should i use a helper or something?

Template sensor that does the math?

Thanks

Bah i give up....... 

Thanks anyway man.

**Comment by GnFlala** [comment]
> HA support that functionality out of the box

I am closing this since i am not going to bother to find out the out of the box thing with multiple commas and whatnot. If anyone needs the same i guess the answer is above.

Thanks again and have fun.

**Comment by elad-bar** [comment]
it appear that i was under wrong impression that unit convert is available but it's just number of digits,
reopening and will add a fix for it

thanks

**Comment by GnFlala** [comment]
also all download rates are always off the chart.

Example my download rate now when line is almost idle.

Received Rate
4,126,565,368.0 B/s
Sent Rate
101 B/s

Rates when line is downloading 47mbps and uploading near 5mbps
Received Rate
4,166,574,455.0 B/s
Sent Rate
537,688 B/s

Its like it incementing the download rates. I think i am going to uninstall and reinstall it something is way off.

**Comment by elad-bar** [comment]
I see it as well, Received Rate == Received Traffic

**Comment by GnFlala** [comment]
if you want to have sensor entities the abbility to choose the units i think that each entity will need 

Device class: data rate
Unit of measurement: B/s

Then the entity will give the user the freedom to choose what he wants. at least that is what i do when i create sensor from node-red

**Comment by elad-bar** [comment]
i added new entity (SELECT) that provides the ability to choose the unit,
once you have choose the unit, it will reload all the devices and interfaces that are monitored.

the recieved rate entity for interface took data from the traffic - type.

I'm testing it and will release new version soon

**Comment by elad-bar** [comment]
release [v2.1.1](https://github.com/elad-bar/ha-edgeos/releases/tag/v2.1.1) with fix for the switch interface and missing functionality of units

**Comment by mikesnook** [comment]
> release [v2.1.1](https://github.com/elad-bar/ha-edgeos/releases/tag/v2.1.1) with fix for the switch interface and missing functionality of units

Functionality for the units are working great here, thanks!

**Comment by GnFlala** [comment]
Its great here as well man. that was blazing fast. 

Thanks once more.

**Comment by mikesnook** [comment]
> Its great here as well man. that was blazing fast.
> 
> Thanks once more.

Blazing fast is right! Very much appreciated.
