### ISSUE TITLE
switch.ubnt_interface_ethX_status has disappeared after 2.1.1 update

### ISSUE THREAD

**Issue by Greminn** [elad-bar/ha-edgeos#135]
Core 2024.5.1
Supervisor 2024.04.4
Operating System 12.2

Integration v2.1.1

The binary_sensor.ubnt_interface_ethX_status entity for each ethernet port has disappeared since the 2.1.1 update. The binary_sensor had some handy attributes, like IP address etc. Note that in the 2.1.0 release they incorrectly changed from a binary_sensor to a switch, in the 2.1.1 they are not available. 

<img width="1021" alt="image" src="https://github.com/elad-bar/ha-edgeos/assets/81659316/05c12ed5-58be-4a55-bce5-245df98074e0">

**Comment by elad-bar** [comment]
please check [v2.1.2](https://github.com/elad-bar/ha-edgeos/releases/tag/v2.1.2)

thanks

**Comment by benjycov** [comment]
Confirmed that 2.1.2 has fixed this, albeit the attribute is now called 'address' and previously is was 'addresses'.

**Comment by Greminn** [comment]
Confirmed as fixed. Does the switch literally switch off the port?

**Comment by elad-bar** [comment]
There are 2 switches, monitored for adding sensors of traffic and status that actually turn off interfaces

**Comment by elad-bar** [comment]
closing as confirmed as fixed
