### ISSUE TITLE
Failed to extract Interfaces data, Error: 'wireguard' is not a valid InterfaceTypes - 

### ISSUE THREAD

**Issue by CatalinGB** [elad-bar/ha-edgeos#139]
Hi,

After updating to 2.1.x version I started getting the following error(at a ~2 errors/second):
`2024-05-06 18:37:28.458 ERROR (MainThread) [custom_components.edgeos.data_processors.interface_processor] Failed to extract Interfaces data, Error: 'wireguard' is not a valid InterfaceTypes, Line: 105`

The debug logs don't show anything more than the above issue.

Version of ha-edgeos: 2.1.2
Homeassistant version: 2024.5.1

Please let me know if I can help with  any additional info.

Thanks, Catalin

**Comment by elad-bar** [comment]
Dup #137
