### ISSUE TITLE
Failed to extract Interfaces data, Error: 'openvpn' is not a valid InterfaceTypes, Line: 105

### ISSUE THREAD

**Issue by TimBeekman** [elad-bar/ha-edgeos#141]
![image](https://github.com/elad-bar/ha-edgeos/assets/89469564/95d6ecc6-d02a-4a03-9773-59dcbbcd7fd3)

I do not have an Interface called OPENVPN. Where does this error originate from?

**Comment by elad-bar** [comment]
Dup #137

**Comment by TimBeekman** [comment]
Closed as duplicate https://github.com/elad-bar/ha-edgeos/issues/137
