### ISSUE TITLE
Updating 2.1.x -  Failed to load EdgeOS, error: , line: 36

### ISSUE THREAD

**Issue by jaztim** [elad-bar/ha-edgeos#144]
Ever since 2.1.0, I've been unable to start this integration. It persists to the latest version. I finally decided this wasn't getting fixed with subsequent updates so I am logging this as an issue.

I get this error: 
Failed to load EdgeOS, error: , line: 36

Sorry, but I tried to get more logging, however, even when I turn on debug, I only see this line.

**Comment by elad-bar** [comment]
did you follow the instructions in other issues (that were closed) to remove and re-add the intergation as this is breaking change version?
if you did and still expirence that error, will need debug log level of it.

thanks

**Comment by jaztim** [comment]
thanks - after removing and re-adding, it is working now

**Comment by elad-bar** [comment]
Thanks for the update

**Comment by TheHolyRoger** [comment]
You should pin this issue...

**Comment by elad-bar** [comment]
@TheHolyRoger will do, thanks for the feedback
