### ISSUE TITLE
Causing problems with automations

### ISSUE THREAD

**Issue by BigHomie90** [elad-bar/ha-edgeos#15]
When i run this integration it works ok but there is a problem with automations in home assistant.
When i try to create an automation, the drop down list refreshes fast, scrolls up by itself and causing lag. I am runnning hass.io 0.107.8. I tried disabling one by one my integrations and plugins and the problem solved when i removed the edge os integration. Do you know how can this be fixed?

**Comment by elad-bar** [comment]
I checked it with just that component and it's not being reproduced, maybe an overload on the client causes it (component is sending updates for each sensor every second),
How many sensor did you create from that component?

**Comment by BigHomie90** [comment]
Maybe you have right about overload... I created 4 sensors for my vlans and one for eth0. I ll check it again and let you know!

**Comment by elad-bar** [comment]
in latest version added new option to change update interval, can you check if changing it to 10/30 seconds makes it work better for you?

thanks

**Comment by elad-bar** [comment]
@BigHomie90  Any updates?

**Comment by BigHomie90** [comment]
Hello again and sorry for the late reply. It seems that your integration works just fine. The "lag"problem is the Automation Editor from home assistant. I started a topic here https://community.home-assistant.io/t/home-assistant-automations-gui-extreme-lag/184750/6 and it seems that a few people have the same issue. BTW your integration is the best. Real time monitoring and let us configure every interface as we want. Thanks for the work and effort you put on this.

**Comment by elad-bar** [comment]
can we close it?

**Comment by BigHomie90** [comment]
Yes , thank you for the support!
