### ISSUE TITLE
403 Forbidden after 00:16am

### ISSUE THREAD

**Issue by sgvj** [elad-bar/ha-edgeos#2]
Every day the edgeOS component stops working at 00:16.
My bandwidth graphs flatline and logs report

> Failed to get devices data, Error: 403, message='Forbidden', Line: 89
> Failed to perform heartbeat, Error: 403, message='Forbidden', Line: 68

Perhaps I set things up incorrectly? I'm using it internally so no TLS.
PS: thanks so much for making this, I really look forward to settings up automations based on this data.

**Comment by elad-bar** [comment]
Hi, can you share the logs and configuration? 

Thanks

**Comment by sgvj** [comment]
In configuration.yaml:

edgeos:
    host: 192.168.1.1
    ssl: true
    username: redacted
    password: redacted
    monitored_interfaces:
        - eth4
        - vtun0
    unit: 'M'

**Comment by sgvj** [comment]
Logs:

custom_components.edgeos.web_api] Failed to perform heartbeat, Error: 403,
message='Forbidden', Line: 68
2019-05-28 10:03:51 ERROR (MainThread) [custom_components.edgeos.web_api]
Failed to get devices data, Error: 403, message='Forbidden', Line: 89

**Comment by sgvj** [comment]
```
dfasdfsa asdfsdf
asdfasdf
asdff
awefa . asefsef
```

**Comment by sgvj** [comment]
I believe this is related to a Let's Encrypt certificate script running daily on my ER-X.
Still testing but closing the issue for now.
