### ISSUE TITLE
Stops every hour

### ISSUE THREAD

**Issue by joostvanmourik** [elad-bar/ha-edgeos#26]
it works perfectly for about an hour and than fails. In the log i see this ;

Entity id already exists - ignoring: sensor.edgeos_unknown_devices. Platform edgeos does not generate unique IDs

Please help

**Comment by elad-bar** [comment]
Please correct me if I'm wrong  - That's not a failure / stops the component, just a warning message, need to check why it happens

**Comment by joostvanmourik** [comment]
HA Receives all interface info for about an hour and then nothing MBytes PS Sent and Received 0

Also found this error ;
2020-05-04 14:00:43 ERROR (MainThread) [custom_components.edgeos.clients.web_socket] Failed to connect on retry #3
