### ISSUE TITLE
Any negative impacts to the router to poll every 1 second? 

### ISSUE THREAD

**Issue by iptvcld** [elad-bar/ha-edgeos#27]
I like the Mbps in and out sensor but thinking is there any impacts

**Comment by elad-bar** [comment]
The polling takes place every 30 seconds and you cannot control it, the update interval is for updating sensors, why?
Basic details are available by polling it from the API, 
Counters (RX/TX, rates, etc...) are being sent to the component via websocket and you can get multiple messages a seconds.

To avoid update upon each message being sent to the component, there is a scheduler that updates the HA components according to the configured interval

**Comment by iptvcld** [comment]
Thanks, I would just want to grab the Mbps Rx and TX sensor and yea updateing every 1 second does make sense. Wad just thinking it must be about of overhead on the router and on HA.

**Comment by elad-bar** [comment]
I'm using it with 1 second interval as well

**Comment by iptvcld** [comment]
is there another way to just grab the edgeOS Mbps reading in realtime and use that in HA - the 1 sec polling seems a bit too much.

**Comment by elad-bar** [comment]
Sorry for getting into semantics, it's not 1 second per polling but for updating the component,  getting the data is being done by push from the router more than 1 time per second,
Anyway, if you would like to update every X seconds you can change it from integration's options to the desired interval in seconds

**Comment by iptvcld** [comment]
Thanks. So if I am not using any device trackers other than the interface mbps sensor. Is the router really being polled?

So as soon as the integration is setup, the router starts pouring in data without any polling and its now up to us to see how often we want to see that data. Do I see it right?

**Comment by elad-bar** [comment]
Every one minute there are 3 calls to get list of:
- device's data -  to identify configuration changes and new device added
- heartbeat for keep alive
- system data to identify router's version / system name changes

Other than that, you are right, statistics are being sent from the router to the component

**Comment by iptvcld** [comment]
is there an option to increase the one min call to get the list of the above items? In my case i just need the data that comes down from the router (Mbps WAN rate)

Perhaps a drop down option to change (scan_interval: ) ?

**Comment by elad-bar** [comment]
I can add it, the question is why...

Did you see an impact on the router in terms of CPU and memory?

Below is the impact on my router... which is nothing, it works exactly like when you open the UI of the router:
![Screenshot_20200513-063901_Chrome](https://user-images.githubusercontent.com/3207137/81768785-8c912c00-94e4-11ea-9977-82833ee8172b.jpg)

**Comment by iptvcld** [comment]
thanks for taking the time to provide information - would be nice to at least have the option (if its not too much to ask)?

**Comment by elad-bar** [comment]
Will separate the interval of getting data via API from the heartbeat calls, the getter's interval will be configurable, will it work for you?

**Comment by iptvcld** [comment]
that would be good! thanks!

**Comment by elad-bar** [comment]
Implemented the change, requests are now working according to the below:
- Login - at startup or when there is disconnection
- Open WebSocket connection and subscribing to events - after login or after reconnect
- Heartbeat - API call / WebSocket message to router - every 30 seconds (hard-coded) - same as in UI
- Update API - consisted with 3 requests - according to configuration, default=60 seconds
  - Get devices details 
  - Get system status
  - Get unknown devices
- Update Entities - based on the data available from the offline requests and messages from WebSocket - according to configuration, default=1 second
- WebSocket message - all the time, offline

**Comment by iptvcld** [comment]
looks good! Thank you
