### ISSUE TITLE
unable to add to integrations

### ISSUE THREAD

**Issue by MagieMalone** [elad-bar/ha-edgeos#30]
running core 110.4, when installed, I don't find  EdgeOs when trying to add integrations.

**Comment by elad-bar** [comment]
Did you install it from HACS first?

Thanks

**Comment by MagieMalone** [comment]
yes, installed from HACS and also visible on the disk:

~ $ cd /config/custom_components/
custom_components $ ls -la
total 32
drwxr-xr-x    8 root     root          4096 Jun  1 11:43 .
drwxr-xr-x   13 root     root          4096 Jun  1 12:13 ..
drwxr-xr-x    7 root     root          4096 Jun  1 11:43 edgeos


reloaded HA for good measure too.

**Comment by elad-bar** [comment]
Is there any error in logs related to edgeos during startup?

**Comment by MagieMalone** [comment]
just rebooted the hassio host, 

config $ grep -i edgeos home-assistant.log
config $

so nothing in the log at all.

**Comment by MagieMalone** [comment]
after upgrade hassos from 4.8 to 4.9 the problem has disapeared

**Comment by thetravellor** [comment]
This is still an issue for me. As with the other user I can see the edgeos files on the file system.
I am running HA under docker however, I have restarted the home assistant docker containers, and cannot see the edgos integration.

I am running Supervised Home Assistant 0.110.5

grep -i edgeos home-assistant.log
2020-06-09 00:50:42 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for edgeos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

**Comment by thetravellor** [comment]
After upgrade to Home Assistant 0.111.0b3 it now seems to be working.

**Comment by elad-bar** [comment]
Great, how it works for you?
Can we close this issue?

thanks

**Comment by MagieMalone** [comment]
yeah seems it works for both of us now

**Comment by MACscr** [comment]
I am having the same issue running 0.112.3. any idea why this keeps happening? Installed through HACS (you should make that clear in your readme), restarted HA a couple times, but still not showing as available under integrations.

![image](https://user-images.githubusercontent.com/1404944/86981138-c92f7b80-c153-11ea-9fb1-eefe702f8861.png)

**Comment by MACscr** [comment]
Ah, guess a browser caching issue? Weird. I dont know, eventually showed up. Tried again after seeing this one https://github.com/elad-bar/ha-edgeos/issues/33
