### ISSUE TITLE
Presence detection 

### ISSUE THREAD

**Issue by danleitch** [elad-bar/ha-edgeos#31]
Hi Elad

firstly thank you for your work here it really amazing!

I have a small problem.
[Picture Entity Card Configuration](https://www.home-assistant.io/lovelace/picture-entity) allows you to show a picture for each state. 
in my instance when i am 'home' my picture changes to a thumbs up emoji
when i'm 'away' my emjoi gives a thumbs down.

The 'Home' state works fine, though the 'Away' state doesn't pic up.

This syntax below is what i have used and it is good i have tested it on a few other entities and it works flawlessly

entity: device_tracker.edge_router_dans_iphone
name: Dan
show_state: true
state_image:
  home: 'https://i.ibb.co/pr3DW5F/Dan-Home.jpg'
  away: 'https://i.ibb.co/k4fk1t4/Dan-Away.jpg'
type: picture-entity

so if take this and change the 'entitie' and the 'states' it works

entity: switch.hallway
name: Light
show_state: true
state_image:
  on: 'https://i.ibb.co/pr3DW5F/Dan-Home.jpg'
  off: 'https://i.ibb.co/k4fk1t4/Dan-Away.jpg'
type: picture-entity

I have a feeling that the 'away' state is not registering properly with HA.

TIA
Dan

**Comment by elad-bar** [comment]
I think away state in UI is just a resource of state = not_home, you can check it in developer -> states

**Comment by elad-bar** [comment]
From home assistant device tracker page:

```
Device states
The state of your tracked device will be 'home' if it is in the home zone, detected by your network or Bluetooth based presence detection. If you’re using a presence detection method that includes coordinates then when it’s in a zone the state will be the name of the zone (case sensitive). When a device isn’t at home and isn’t in any zone, the state will be 'not_home'.
```

**Comment by danleitch** [comment]
Thank you for this... 

for any one in the future it's 'home' and 'not_home'

see below

https://community.home-assistant.io/t/card-to-show-who-is-home/137726/3
