### ISSUE TITLE
Some monitored_devices appear as disconnected

### ISSUE THREAD

**Issue by Wojcioo** [elad-bar/ha-edgeos#32]
Hello
Some of my monitored devices appear as disconneted, but they are on and they respond to ping.
These are two wireless cameras, one apears as off:
![obraz](https://user-images.githubusercontent.com/33394332/85111345-7d547b00-b214-11ea-9431-a338d36c6156.png)
but with the second everything is fine.
![obraz](https://user-images.githubusercontent.com/33394332/85111441-9f4dfd80-b214-11ea-803c-f725a2d62a50.png)
Such situation is also with wired devices.
Synology apears as on:
![obraz](https://user-images.githubusercontent.com/33394332/85111662-f358e200-b214-11ea-9b8b-8e5bdf9fcede.png)
but my alarm device look off:
![obraz](https://user-images.githubusercontent.com/33394332/85111881-3adf6e00-b215-11ea-8d4d-a63abac54ae1.png)

**Comment by elad-bar** [comment]
If no traffic detected for the last 3 minutes it will appear as disconnected,
can you check if you see there is traffix (RX/TX) in EdgeOS web admin when it happen?

thanks

**Comment by Wojcioo** [comment]
yes, there is traffic.....
![obraz](https://user-images.githubusercontent.com/33394332/85205772-bd535500-b31d-11ea-86da-8c337dc6ca9e.png)
but in HA this entity is off since yestarday
![obraz](https://user-images.githubusercontent.com/33394332/85205790-dcea7d80-b31d-11ea-8642-2c2664e8e648.png)

**Comment by bryeartem** [comment]
I am also having the same issue, these devices all currently have data in use, (they are my access points, cameras, even while streaming show disconnected.)  
![Screen Shot 2020-06-23 at 10 03 50 PM](https://user-images.githubusercontent.com/45539718/85489578-32cd5880-b59e-11ea-9f75-4f7017582c1f.png)
![Screen Shot 2020-06-23 at 10 08 51 PM](https://user-images.githubusercontent.com/45539718/85489585-33fe8580-b59e-11ea-992e-766f91b5869e.png)

**Comment by Wojcioo** [comment]
Hello
Any news?

**Comment by elad-bar** [comment]
@Wojcioo, can you please check the log level to DEBUG and also check the integration's options - log incoming messages as well, with that information I might be able to understand the reason

thanks

**Comment by Wojcioo** [comment]
> @Wojcioo, can you please check the log level to DEBUG and also check the integration's options - log incoming messages as well, with that information I might be able to understand the reason

I've done it, but I can click check box "Save debug file", but it doesn't want to stay on...

![image](https://user-images.githubusercontent.com/33394332/102227726-30631000-3eea-11eb-9fa0-0ab857ba6d86.png)

**Comment by bryeartem** [comment]
I also cannot get save debug file to actually save the debug file.

**Comment by shlomki** [comment]
@elad-bar I'm also having the same problem, some devices are appearing as disconnected even though I see that their Attributes are getting updated every 5 seconds and are showing traffic.
I tried saving the log but I'm getting an error:

```
2021-08-06 21:51:37 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/edgeos/__init__.py", line 61, in async_options_updated
await handle_log_level(hass, entry)
File "/config/custom_components/edgeos/helpers/__init__.py", line 66, in handle_log_level
await hass.services.async_call(DOMAIN_LOGGER, SERVICE_SET_LEVEL, log_level_data)
File "/usr/src/homeassistant/homeassistant/core.py", line 1438, in async_call
raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service logger.set_level
```

Any chance you can take a look to help us all out?

**Comment by shlomki** [comment]
@Wojcioo @bryeartem
I've found the problem and have fixed the bug, looks like all of the devices that were previously disconnected are now getting updated properly and they appear as connected.

I've created a pull request for @elad-bar with the bug fix, I hope he would approve of the pull request and merge it into his repository.

In the meantime you can update the following file under `/custom_components/edgeos/managers/data_manager.py` and it should fix the problem for you.

Just download this file and replace with yours, or copy and paste the contents:
https://github.com/shlomki/ha-edgeos/blob/monitored_devices_disconnected_fix/custom_components/edgeos/managers/data_manager.py

**Comment by elad-bar** [comment]
@shlomki please read my comment, I don't think you have fixed it, just update the last update once there was an activity once,
Means that if one device is on, it will remain on up until you will reset the component, 
If you can confirm you have checked the scenario, please share more details,

Thanks

**Comment by shlomki** [comment]
How I tested:
1. Installed your integration without changes.
2. Configured away interval to 60 seconds.
3. Device X appears as disconnected (even though it's connected).
4. Applied my bugfix.
5. Restarted HA.
6. Device X now appears as connected.
7. Waited 24 hours just to make sure - device still appears connected.
8. Now I've **physically** unplugged the device and waited 60 seconds - **device updated to disconnected**.
9. Waited 3 mins and plugged the device back in - **the device was updated to connected**.

**Comment by elad-bar** [comment]
@shlomki thanks for the detailed test, merged PR after checking why it works,
In first iteration of each device traffic is being stored after setting the activity last check which makes it work only if there was inbound and outbound traffic,
With your fix it takes it from the response directly 

Thanks!
