### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by golddragon007** [elad-bar/ha-edgeos#35]
Hello,
I have now similar issue like in the #25 happened. I continuously getting Invalid credential errors when I try to attach my device.
According to HACS I've the a395fc3 commit version, which seems the newest master.

**Comment by elad-bar** [comment]
Did you create a dedicated username and password? 
Can you attach logs (debug level)?

Thanks

**Comment by golddragon007** [comment]
Hello @elad-bar 
Logs are here:
EdgeOS password is not encrypted, please remove integration and reintegrate
11:50:52 – Ubiquiti EdgeOS Routers (WARNING) - message first occurred at 11:50:49 and shows up 2 times
Cannot complete login
11:50:52 – Ubiquiti EdgeOS Routers (WARNING)
Failed to login EdgeOS EdgeOS due to HTTP Status Code: 403
11:50:52 – Ubiquiti EdgeOS Routers (WARNING)
Failed to login, Invalid credentials
11:50:52 – Ubiquiti EdgeOS Routers (ERROR)

I also using IP as a host address.
Yes, I have a dedicated user with operator level. I can log in with it from the UI.
Also, I didn't have previously integrated EdgeOS.

**Comment by elad-bar** [comment]
Which version of edgeos installed?
The log you've posted is for warning message,
Can you please change it to debug first then try to add?

**Comment by golddragon007** [comment]
I need to put this:
```
logger:
  default: warning
  logs:
    custom_components.edgeos: debug
```
Into configuration.yaml no? I've done that and I've got those what I've previously sent.

v2.0.8-hotfix.1 is the current running version.

**Comment by elad-bar** [comment]
Weird... are you extracting the logs from HA or the log file?
I don't see the message of trying to open the integration form

Thanks

**Comment by golddragon007** [comment]
I've used the log page in the config page, but it seems to debug level stuff is not visible there, now I've checked the log file itself:
```
2020-07-10 13:30:23 DEBUG (MainThread) [custom_components.edgeos.config_flow] Starting async_step_user of EdgeOS
2020-07-10 13:30:49 DEBUG (MainThread) [custom_components.edgeos.config_flow] Starting async_step_user of EdgeOS
2020-07-10 13:30:49 WARNING (MainThread) [custom_components.edgeos.managers.password_manager] EdgeOS password is not encrypted, please remove integration and reintegrate
2020-07-10 13:30:52 ERROR (MainThread) [custom_components.edgeos.clients.web_api] Failed to login, Invalid credentials
2020-07-10 13:30:52 WARNING (MainThread) [custom_components.edgeos.managers.config_flow_manager] Failed to login EdgeOS EdgeOS due to HTTP Status Code: 403
2020-07-10 13:30:52 WARNING (MainThread) [custom_components.edgeos.config_flow] Cannot complete login
2020-07-10 13:30:52 WARNING (MainThread) [custom_components.edgeos.managers.password_manager] EdgeOS password is not encrypted, please remove integration and reintegrate
```

**Comment by golddragon007** [comment]
After debugging the code, I've found the problem. In the `credentials = {CONF_USERNAME: username, CONF_PASSWORD: password}` line in `custom_components/edgeos/clients/web_api.py:102` place the password represented as the hashed version instead of the plain text. And the login page doesn't accept just the original one.
https://github.com/elad-bar/ha-edgeos/blob/master/custom_components/edgeos/managers/configuration_manager.py#L47 In this point I have a password but it looks like a hashed one and not an encrypted one.
And I've found the issue, my password hash doesn't finished with '=', so this condition is not OK:
https://github.com/elad-bar/ha-edgeos/blob/master/custom_components/edgeos/managers/password_manager.py#L38
After I've removed the condition and always decoding I was able to login to my EdgoOS.

**Comment by elad-bar** [comment]
Please check if it works for you with latest version

## 2020-07-23

**Implemented enhancements:**

- Moved encryption key of component to .storage directory
- Removed support for non encrypted password (**Breaking Change**) 

**Fixed bugs:**

- Better handling of password parsing

**Comment by elad-bar** [comment]
@golddragon007, can you please check if it works for you with the new release?

Thanks

**Comment by golddragon007** [comment]
It's working now.
