### ISSUE TITLE
[question] monitored device appears to connect although it's not physically there

### ISSUE THREAD

**Issue by leonardpitzu** [elad-bar/ha-edgeos#39]
I have a few phones i track in order to trigger home and not_home events in HA. All but one device are working as expected. The troubled device has following behavior: when leaving home it triggers HA and not_home is registered. In 3-5min the phone is "seen" as connected to the router and thus HA "thinks" i arrived home. 3-5 minutes later the phone appears again as not connected to the router and HA again triggers the not_home event. This happens only to 1 device (iphone XS) where all other devices work correctly and as expected. The device has static IP lease. Any ideas where to start to debug this? All other devices are set up in exactly the same way.

**Comment by elad-bar** [comment]
it can be that the device doesn't work with ARP commands as other devices, iOS for instance causing that behaviour at my network as well, if that's the case, the only way to solve it is by defining an increased threshold for the `seen`, 
will work on that and release new version in the upcoming week

thanks

**Comment by nfacha** [comment]
> it can be that the device doesn't work with ARP commands as other devices, iOS for instance causing that behaviour at my network as well, if that's the case, the only way to solve it is by defining an increased threshold for the `seen`, will work on that and release new version in the upcoming week
> 
> thanks

Im also facing this issue, what is the `seen` you refer to? The time to consider away thing?

**Comment by elad-bar** [comment]
can you please let me know if with v2 the issue still happens?

thanks

**Comment by elad-bar** [comment]
closing issue as there are no updates
