### ISSUE TITLE
incomplete list of devices in options menu

### ISSUE THREAD

**Issue by jwws** [elad-bar/ha-edgeos#41]
In the "options for EdgeOS" dialog, the two dropdowns for "monitored devices" and "tracked devices"
only show a fixed number of devices with checkboxes (I see 7 in each).  However, I have more than 7 devices, and don't seem to have a way to select/add them.  There's a reference to using a CSV list, but nowhere to put that.  The component sees all of my devices (they're listed in the "unknown devices" sensor).

I'm guessing this is just a UI bug to not have the full list of devices to select for monitoring+tracking?  I'm happy to manually add them to a file, but it would help if the options dialog would describe where to do that, if it can't be done there.

**Comment by elad-bar** [comment]
Are all devices configured as static ips?

**Comment by jsp196** [comment]
I know this is an old thread, but do the monitored devices need to have static IPs to work?  So for example, if I want to use it as presence for my cell phone, I would need to set a static IP for my phone?

**Comment by elad-bar** [comment]
Yes, otherwise your device can change its IP, what would you track in that case?

**Comment by kkplein** [comment]
@elad-bar well, the mac address for example..?

I found this thread, because in our case, the dropdown for both monitored and tracked devices are empty and I can also not type an IP there. Is this, because this only works with fixed IPs, and not dhcp-ed IPs..? (which is what I am using for wifi devices)

**Comment by jsp196** [comment]
It will only work for static IPs.  Dev made a good point - if the IP changes, you would be incorrectly marked away.

**Comment by kkplein** [comment]
I don't understand. A mac address usually persists, even in case dhcp handed out a different ip address.
Anyway: not using fixed IPs here, so that's probably why my dropdown is empty, and I cannot use this integration for presence.
Nice integration anyway, thanks for it!

**Comment by jsp196** [comment]
Sorry I misread what you said - it does not use MAC though that would actually be a great way to do it.  @elad-bar Could you add MAC tracking integration?

**Comment by elad-bar** [comment]
Will check it and update how it works

**Comment by bjs-pdx** [comment]
I too would appreciate the ability to monitor/track via MAC.  This actually makes sense as you have rightly indicated IP addresses can change, but MACs remain constant.  (Except on Apple products which can hide the real MAC for wireless, but that's a different issue.)  :-)

**Comment by kkplein** [comment]
Is there any update here..? Seems mac addresses still cannot be used..? (sorry: no, I don't have the skills to add this feature myself...)

**Comment by elad-bar** [comment]
tracking by mac is not feasible as the router doens't support it,
for static ips there is continuous update, for leased devices there is only expiration since created, once getting to the expiration the device's expiration will get prolonged or removed.
