### ISSUE TITLE
Doesn't work with EdgeOS v2.x

### ISSUE THREAD

**Issue by rtrainer** [elad-bar/ha-edgeos#42]
Just commenting that there should probably be a disclaimer in the repo and the HASS information screen that this only works with v1.x

I have found some documentation that someone is putting together for the API, https://github.com/matthew1471/EdgeOS-API/tree/master/Documentation.

Not sure if this is valid for both versions.

**Comment by elad-bar** [comment]
I'm working with v2 since it was released,
Can you please provide more details?

**Comment by rtrainer** [comment]
I have an EdgeRouter 4 running EdgeOS 2.09. Looking at it this morning, it appears that I need to turn on DPI and TA export. It looks like I overlooked this in the installation instructions.
