### ISSUE TITLE
Firewall rule - Port / protocol to be accepted for integration to work

### ISSUE THREAD

**Issue by argoeng** [elad-bar/ha-edgeos#43]
Hi guys, the integration worked fine for me until I moved all devices and HA raspberry in a VLAN without access to the router. I'd like to add a firewall rule for this purpose so can you please tell which port and protocol should be accepted?
Thanks for your consideration,
Argoeng

**Comment by elad-bar** [comment]
Hi, it opens a WebSocket / API connections using port 443

**Comment by elad-bar** [comment]
Any news?

**Comment by argoeng** [comment]
Hi elad-bar! Your advice works fine, thanks!

For anyone who needs it, below how I configured the firewall policy:
Add a new rule in the ruleset for VLAN interface with direction: LOCAL. Action: accept; protocol: TCP; state: new; source address: IP address of the machine where HA runs; destination address: VLAN IP address of the router; port: 443.
Configure integration accordingly.
It should work!
Argoeng
