### ISSUE TITLE
Failed to connect EdgeOS WS

### ISSUE THREAD

**Issue by gjohansson-ST** [elad-bar/ha-edgeos#45]
`2021-01-18 11:46:40 WARNING (MainThread) [custom_components.edgeos.clients.web_socket] Failed to connect EdgeOS WS, Error: 400, message='Invalid response status', url=URL('wss://192.168.10.1/ws/stats')`

As per latest HA version (core-2021.1.4)

**Comment by elad-bar** [comment]
Dup #44
