### ISSUE TITLE
After upgrade to HA Core core-2021.1.4 Several parameters stop working

### ISSUE THREAD

**Issue by Husabert** [elad-bar/ha-edgeos#46]
Hi,
After the recent upgrade to HA core-2021.1.5 several parameters of the integration stop working.
binary_sensor.edgeos_system_status and sensor.edgeos_unknown_devices still work.
However the sensors or the individuals ports (eth0 ..) and system uptime no longer work.
Any idea how to resolve?

**Comment by jdubz666** [comment]
+1

I also cannot see Bytes received and sent per device

**Comment by elad-bar** [comment]
For me it's working well,
What version of edgeos are you using?
Are you sure that DPI settings are on?

Thanks

**Comment by Husabert** [comment]
Hi 

Thanks for the reply,
I'm on EdgeRouter X v1.10.10. (running on a ER-X)
Traffic Analysis is set to Operational Status Enabled. 
I have not setup DPI since there was/is no need. 
Previously all Parameters worked.

**Comment by Husabert** [comment]
Hi,

Something else that caught my attention in EDGE OS was the increasingly large number of Active Sessions of the HA user .
In the end this leads to a unresponsive Edge router.
Is there a way to for the integration to log off? 
I tried with Clear Credentials on and off, but no result.

**Comment by Husabert** [comment]
When replaying the process of switching traffic analysis on and off I learned that in the current setting (Enabled) DPI is by default switched on.

**Comment by elad-bar** [comment]
Following feedbacka from the last 2 weeks of people who upgarded their firmware to 1.10.10 is that it stopped working, please upgrade to 2.x and it will work for you again

Thanks

**Comment by Husabert** [comment]
Thanks for the reply.

Issue occurred before I upgraded to 1.10 (was on 1.07 or months)  The upgrade to 1.10 was to try if this resolved the issues on HA
As to Edge OS 2.x: I upgraded to 2.09 just now. Still the same issues

**Comment by Husabert** [comment]
Success! Took some reboots of both HA and router, but okay now! Thanks!
