### ISSUE TITLE
Not able to find integration in HACS and Supervisor add-ons store

### ISSUE THREAD

**Issue by damian-zygmuntowicz-siili** [elad-bar/ha-edgeos#47]
Not able to find integration in HACS and Supervisor add-ons store

**Comment by cclarke99** [comment]
I can find it in HACS but once installed it does not show in the list of integrations to add. @damian-zygmuntowicz-siili @elad-bar

**Comment by cclarke99** [comment]
> I can find it in HACS but once installed it does not show in the list of integrations to add. @damian-zygmuntowicz-siili @elad-bar

Apparently my browser cache was the problem. After forcing a reload of the UI (via browser refresh), the integration finally showed up.
