### ISSUE TITLE
 EdgeOS WS, Error: 400

### ISSUE THREAD

**Issue by Chen2022** [elad-bar/ha-edgeos#51]
Logger: custom_components.edgeos.clients.web_socket
Source: custom_components/edgeos/clients/web_socket.py:91
Integration: Ubiquiti EdgeOS Routers (documentation)
First occurred: 16:06:24 (261 occurrences)
Last logged: 16:43:09

Failed to connect EdgeOS WS, Error: 400, message='Invalid response status', url=URL('wss://192.168.88.1/ws/stats')

**Comment by elad-bar** [comment]
Can you please provide debug level logs to understand the root cause?
Does it happen upon startup, setup or after during ongoinh usage?

Thanks

**Comment by Chen2022** [comment]
It appears at startup
Sorry, I don't know where the debug level log is
[home-assistant.log](https://github.com/elad-bar/ha-edgeos/files/7011156/home-assistant.log)

**Comment by Chen2022** [comment]
The device tracker has been out of state
Edgeos system status connected
![image](https://user-images.githubusercontent.com/70124937/129994817-936257b2-de99-41d7-8012-35b54ea150a5.png)
![image](https://user-images.githubusercontent.com/70124937/129995016-1391f512-892a-41dc-8e0f-0985936f89b9.png)

**Comment by Yorik-Code** [comment]
Same fault here. Will increase logging and send back.

**Comment by Chen2022** [comment]
[edgeos_data.log](https://github.com/elad-bar/ha-edgeos/files/7029040/edgeos_data.log)
What's the problem, please? Thank you

**Comment by elad-bar** [comment]
Which version of edgeos are you using?

Thanks

**Comment by Chen2022** [comment]
> Which version of edgeos are you using?
> 
> Thanks

EdgeRouter X v1.10.11

![image](https://user-images.githubusercontent.com/70124937/130393273-edda93fb-ba1d-4490-89c7-a5d0f35779e2.png)

**Comment by elad-bar** [comment]
V1 is no longer supported, will update the README and error

**Comment by Chen2022** [comment]
OK, do I need to upgrade to which version to support it

**Comment by Chen2022** [comment]
> V1 is no longer supported, will update the README and error

OK, do I need to upgrade to which version to support it

**Comment by elad-bar** [comment]
yes (if you would like to), will release a new version soon with the error log and prevent it to get installed,
I suggest to read the release notes and in forums as there are some issues after upgrading that needed to get solved by configurations, anyway, you should have backup of the previous FW and configurations

**Comment by Chen2022** [comment]
> yes (if you would like to), will release a new version soon with the error log and prevent it to get installed,
> I suggest to read the release notes and in forums as there are some issues after upgrading that needed to get solved by configurations, anyway, you should have backup of the previous FW and configurations

OK, thank you
