### ISSUE TITLE
interface bandwidth usage history

### ISSUE THREAD

**Issue by OneCyrus** [elad-bar/ha-edgeos#57]
it would be great to have bandwidth usage sensors so we could visualize them in charts. currently it's only tracked as attributes which don't have history by themself.

**Comment by Lenbok** [comment]
Indeed, this would be nice! I'm currently achieving via template sensors, but it's a bit time consuming to set up if you have a lot of devices.

**Comment by elad-bar** [comment]
Please check the latest version v1.2.0, it supports all measurements via sensors instead of attributes

**Comment by Lenbok** [comment]
From my initial look it seems that per device rates are not working (they have no values).  (Per device traffic, and per interface traffic and rates look OK).

**Comment by elad-bar** [comment]
thanks , fixed it will release a new version soon

**Comment by elad-bar** [comment]
Available in v1.2.2
