### ISSUE TITLE
uptime

### ISSUE THREAD

**Issue by lineargraphics** [elad-bar/ha-edgeos#58]
Is there a way to change uptime from seconds to days or even hours?

**Comment by elad-bar** [comment]
can you please share the motivation?

thanks

**Comment by lineargraphics** [comment]
normally we don't quantify time in seconds alone so it maybe more informative to have days, hours and seconds

**Comment by elad-bar** [comment]
the EdgeOS reports it as seconds, nothing I can with it,
the right solution would be to present it as date/time but again, not supported by the device.

**Comment by lineargraphics** [comment]
Ok no worries

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
