### ISSUE TITLE
No dropdown for Tracked Devices

### ISSUE THREAD

**Issue by peterbeeston** [elad-bar/ha-edgeos#62]
v1.1.7
HA core-2021.12.0, supervisor-2021.12.1, Home Assistant OS 7.0
Confuguration dropdown for Tracked Devices does not exist:
![edgeint](https://user-images.githubusercontent.com/10382070/145733460-de38aa4b-473c-45ca-8d07-1ee5e1566db2.jpg)

**Comment by elad-bar** [comment]
can you please try to unistall and install the component, for me it works, probably cache issue
if still not working, please change log level of component to debug, get to the options and post the log

thanks

**Comment by peterbeeston** [comment]
I have uninstalled, re-downloaded from HACS and re-installed. Still no Tracked Devices dropdown.
Changed component log-level to debug
Homeassistant log attached
[home-assistant.log](https://github.com/elad-bar/ha-edgeos/files/7737917/home-assistant.log)
.

**Comment by peterbeeston** [comment]
Restarted HA with debug level set on log. Component failed to start with the the following in the log:
This error originated from a custom integration.

Logger: custom_components.edgeos
Source: custom_components/edgeos/__init__.py:40
Integration: Ubiquiti EdgeOS Routers (documentation)
First occurred: 21:46:18 (1 occurrences)
Last logged: 21:46:18

Failed to load EdgeOS, error: Unable to find service logger.set_level, line: 27

Monitored devices
Monitored interfaces
Tracked devices
All have no dropdowns in component config.

**Comment by Adirael** [comment]
@peterbeeston do you have your devices configured with static mapping? Only those devices will show on the config, if no devices are there nothing will be shown.

https://github.com/elad-bar/ha-edgeos/issues/56

**Comment by elad-bar** [comment]
@peterbeeston as @Adirael mentioned, did you set these devices with static mapping?

thanks
