### ISSUE TITLE
Disconnected wireless device appears connected

### ISSUE THREAD

**Issue by leejunweisg** [elad-bar/ha-edgeos#64]
Hello!

I just installed this integration and everything went smoothly! I proceeded to add a device to both "Monitored devices" and "Tracked devices", and I can see them appear "Connected" and "Home".

However, when I disconnect this device from the network (by turning off the wifi on my MacBook), both the entities does not change to "Away" and "Disconnected", even after 3 minutes, which is the default "Consider away interval". 

May I know where could I start troubleshooting this, or is there an explanation for this behaviour? Thanks!!

**Comment by nfacha** [comment]
Im also facing this issue

**Comment by elad-bar** [comment]
can you please provide the debug file (directly to my email - elad.bar@hotmail.com),
to extract the file use service:
```yaml
service: edgeos.generate_debug_file
data: {}
```

to be able to understand the issue, i will need a debug file while device is connected and another one after 4 minutes the device was disconnected (turned off or removed from network)

thanks

**Comment by elad-bar** [comment]
can you update if it still happens with v2.x?

thanks

**Comment by elad-bar** [comment]
closing issue as not updates for long time
