### ISSUE TITLE
monitored_devices all appear as disconnected

### ISSUE THREAD

**Issue by sebastian-ruiz** [elad-bar/ha-edgeos#7]
The component seems to be working and I can see the uptime of my Edgerouter X.
What does not seem to be working is the connected status of my devices. It can read the correct Mac and IP address of the devices, but it always shows disconnected. In `device_tracker` it always shows `away`. The screenshots below provide more details:

<img width="417" alt="Screenshot 2019-09-29 at 14 09 46" src="https://user-images.githubusercontent.com/2012398/65832376-f8f74c00-e2c2-11e9-96b3-fd460973989d.png">
<img width="380" alt="Screenshot 2019-09-29 at 14 10 21" src="https://user-images.githubusercontent.com/2012398/65832380-fdbc0000-e2c2-11e9-9b9d-dd3453b9130d.png">

**Comment by elad-bar** [comment]
hi, @vephinx , can you please try to connect to the router directly and check what happens with the data over there so it will assist me to understand the cause?

In the router portal, go to Traffic analysis, do you see the device over there?
Is the device defined as static ip?

thanks

**Comment by sebastian-ruiz** [comment]
I forgot to set `traffic analysis` to `enabled`. Sorry for the trouble.
