### ISSUE TITLE
WAN external IP

### ISSUE THREAD

**Issue by danlo315** [elad-bar/ha-edgeos#71]
Hello,

Prior to the new version dropping there is a way to show external IP for the WAN interfaces.  Would it be possible to bring that back?

Prior sensor value: binary_sensor.edgeos_interface_eth[x]_wan.Address

**Comment by danlo315** [comment]
To follow up on why I'm using this: I utilize the edgerouter for WAN failover and I look at the external IP for the entire network, compared to each WAN to see if I'm on primary vs backup.

**Comment by elad-bar** [comment]
I will add it in the next release as attribute related to the specific interface

**Comment by elad-bar** [comment]
new release v2.0.4 with the FR
please review the switch of the status interface, it should include the address,
please update how it works for you

**Comment by danlo315** [comment]
@elad-bar  - just refreshed to 2.0.4 and the addresses attribute is now attached to the status entity.  This is great, thank you so much!

**Comment by elad-bar** [comment]
released v2.0.5, 
since enabling / disabling the interface requires `admin` role,
for intergations logged in with `operator` role based user, there will be a binary sensor instead of switch with the same details

**Comment by danlo315** [comment]
Question: I'm starting to see the IP address rotate between DHCP and actual IP addresses frequently. 

Addresses
dhcp

**Comment by elad-bar** [comment]
Not sure I understand, to which interface? Do you have debug data files for both scenarios?
If not, as part of the integration there is a switch of store debug data,
It will create 3 files begins with the pattern edgeos.{entry_id}.debug.{ws|api|ha}.json.
These files located under .storage directory in the ha config directory.

Please post the relevant data from each of the 3 files

Thanks
