### ISSUE TITLE
Calculating UpTime from Last Restart

### ISSUE THREAD

**Issue by jsp196** [elad-bar/ha-edgeos#72]
I can't seem to find the "uptime" information in the new version of the HA integration.  Is there a way to find this?  Or a way to calculate up time from the Last Restart date/time?  I have a sensor in HA that shows "Internet has been online for:" and then the uptime of the system.  Any guidance would be great.

**Comment by elad-bar** [comment]
you should have `{EdgeOS name} Last Restart` sensor with the last restart date

**Comment by jsp196** [comment]
I saw that, but there used to be an UPTIME sensor that showed the number of seconds the system had been online.  How can I convert "Last Restart Date" to the duration the system has been online?

**Comment by elad-bar** [comment]
Changing the number of seconds every second can increase the db size and HA dev team recommended change all sensors with uptime to start time so in graphs (grafana or any other tool) you can use it as time since

**Comment by doublepedaldylan** [comment]
HACS documentation is outdated on that front then, fyi.

**Comment by elad-bar** [comment]
That's right will update the documentation, thanks

**Comment by jsp196** [comment]
For those who still want "elapsed time" instead of boot time, I was able to still use this template with slight modification and still get the right result.  Just make sure to turn off logging for this particular sensor.

```
  - platform: template
    sensors:
      edgeos_uptime:
        friendly_name: "EdgeOS Network Uptime"
        value_template: >-
          {%- set uptime  = now().timestamp() - states('sensor.edgerouter_5_poe_last_restart')|as_timestamp | round -%}
          {%- set sep     = ', ' -%}
          {%- set TIME_MAP = {
              'week': (uptime / 604800) % 10080,
              'day': (uptime / 86400) % 7,
              'hr': (uptime / 3600) % 24,
              'min': (uptime / 60) % 60
          }
          -%}

          {%- for unit, duration in TIME_MAP.items() if duration >= 1 -%}
            {%- if not loop.first -%}
              {{ sep }}
            {%- endif -%}
              
            {{ (duration | string).split('.')[0] }} {{ unit }}

            {%- if duration >= 2 -%}
              s
            {%- endif -%}
          {%- endfor -%}

          {%- if uptime < 1 -%}
            just now
          {%- endif -%}
```
