### ISSUE TITLE
Where are the temperature, voltage, current and power usage sensors?

### ISSUE THREAD

**Issue by bistek22** [elad-bar/ha-edgeos#81]
Home Assistant v2022.10.05
ha-edgeos v2.0.14

I have updated ha-edgeos to the latest version and the most important things, voltage, current, consumed power and temperature are all gone. I cannot see the entity with these sensors, I have already re-installed and it did not work. How to fix it?

Before the upgrade, I was using version 1.2.6

**Comment by elad-bar** [comment]
Can you please refer me to the documentation where it was supported?
I wrote the integration of v1 and v2, never added these sensors, not sure how to extract them over the API

**Comment by bistek22** [comment]
screenshot below. In earlier versions, there were attributes from which this data could be extracted. In the latest version, the attributes do not appear :)

![Zrzut ekranu 2022-10-23 122731](https://user-images.githubusercontent.com/72106904/197387394-76bbf06f-f983-4600-bd3a-a2281ecf4713.png)

**Comment by elad-bar** [comment]
not sure where you got these attributes, never saw it before :)
can you please share data from the API / WS by opening the router / switch web UI with developer tools?

if data available over there, i have no problem adding it.

thanks

**Comment by elad-bar** [comment]
@bistek22 any updates?

**Comment by bistek22** [comment]
Sorry I didn't write anything, but I was on vacation without a computer. Unfortunately, I don't know how to make the router API accessible with the developer tools :(

**Comment by elad-bar** [comment]
since that information is not available over the API and you couldn't provide details about the integration I can't assist with that issue, if you find more details, please reopen

thanks
