### ISSUE TITLE
Device Tracker shows as Away even though it is connected

### ISSUE THREAD

**Issue by celindho** [elad-bar/ha-edgeos#82]
The WiFi devices (e.g. phones) connect to a WiFi access point and even though the devices are connected, they show up as Away in the integration. 
The WiFi Access Point is provided by a separate device (ASUS RT-AC68U that is directly connected to the EdgeRouter X)

**Comment by elad-bar** [comment]
can you please provide screenshots graphs of the sensors related the rate (incoming / outgoing) of one the devices?
the calculation whether device is away or home is being done based on the traffic it uses, meaning, device without traffic for 180 second considered as AWAY.

thanks

**Comment by celindho** [comment]
Ok, did not realize it takes it from the traffic. It does show them properly when the device is in use.
