### ISSUE TITLE
Are you considering supporting UISP controller or EdgeSwitch?

### ISSUE THREAD

**Issue by KleinerSource** [elad-bar/ha-edgeos#85]
The UISP controller is similar to the UNIFI controller Support almost all edge product management.

**Comment by elad-bar** [comment]
Basically yes, it uses the same api, but i don't have such device to tell you for sure,
You can install the integration, try to integrate into your device and report

Thanks

**Comment by elad-bar** [comment]
any updates on that?

thanks
