### ISSUE TITLE
No longer see any edgeos rate statistics after latest update

### ISSUE THREAD

**Issue by lordpengwin** [elad-bar/ha-edgeos#86]
In home assistant I was monitoring entities related to Internet rates one eth0. Now after the latest update those entities are no longer available and all i see are device related entities but none of them report any rate statistics. I believe the number of available entities for the integration dropped from about 51 to 25.

I'm using an Edge Router X with firmware v2.0.9-hotfix.4

**Comment by elad-bar** [comment]
What version was installed before?

**Comment by lordpengwin** [comment]
I'm sorry, i don't know but i only installed the add-on a month or two ago, the Edge Router firmware has not changed for a long time.

**Comment by elad-bar** [comment]
Please read the readme file for more details,
I have applied major refactor to the component to make it work faster, with less resources and easier maintenance,
Part of it that I changed the configuration,
For each device or interface there is a switch to enable / disable the monitoring,
In addition, another switch allows you to turn on and off specific interface

**Comment by lordpengwin** [comment]
Thanks my problem was that I had to enable monitoring for my device/interface.
