### ISSUE TITLE
Device Sensors change even though device is disconnected

### ISSUE THREAD

**Issue by chi-wi** [elad-bar/ha-edgeos#88]
I activated device tracking for my phone; the addon recognizes when the device is connected.

Once I disable my phone's wifi I **expect** the received traffic to stop changing.
The Edgerouter analytics show that there is no traffic from that device.

However, the addons sensors keep changing (Received Rate, Received Traffic).

I would expect the HA sensors to stop changing.

~~Even though the device away interval is set to 180 seconds, the device tracker does not change.~~

Edit: The device tracker switches to 'away' after around 20 min. Might this be related to the changing sensors?

Any help would be appreciated!

**Comment by elad-bar** [comment]
Not sure i understand the issue

**Comment by chi-wi** [comment]
> Not sure i understand the issue

I reworded it, must have been very tired -- Sorry!

**Comment by elad-bar** [comment]
The HA component is taking the values from the router, would appreciate if you can send logs at the period of time between the device switched off (and you see it as 0 traffic in edge UI) until the koment the status of the device tracker got changed,
That's the only way i can understand why...
Thanks

**Comment by elad-bar** [comment]
any updates?

thanks

**Comment by elad-bar** [comment]
can I close this issue?

thanks

**Comment by chi-wi** [comment]
Sorry! Havent really found the time to check it out! I will open another issue if I find anything, and will make sure to decsribe any weird behaviour more accurately
thanks!

**Comment by elad-bar** [comment]
Keeping the issue open, please update once you are getting to it

**Comment by chi-wi** [comment]
Had to switch away from EdgeOS, closing topic.
