### ISSUE TITLE
Not working on 2.0.9.hotfix5

### ISSUE THREAD

**Issue by dolenec** [elad-bar/ha-edgeos#89]
After update to hotfix5 it stopped working (no data received)..
On hotfix4 it was working..

**Comment by elad-bar** [comment]
I'm also on hf5 and it works for me, can you pls share some logs in debug level so I can try understand the issue?

Thanks

**Comment by dolenec** [comment]
Started working after HA restart..

**Comment by elad-bar** [comment]
great, thanks for the update
