### ISSUE TITLE
Tracking devices without having to provide list

### ISSUE THREAD

**Issue by skylord123** [elad-bar/ha-edgeos#9]
I was using another custom edgeos component and it allowed me to specify `track_new_devices` and not specify a list to track.

I want it to track every device even when new devices get added which it currently does not support.

**Comment by elad-bar** [comment]
Added it to the list, will work on that once I'll have time

**Comment by skylord123** [comment]
@elad-bar much appreciated :)

**Comment by elad-bar** [comment]
I changed the way it works so you don't need to restart after every device added - just set it through UI, why?
I have more than 100 devices at my network, if I set it to montior all devices it will create junk device trackers that I'm not planning to monitor (~95 devices).

I can add a flag that it will add any new device but I don't see anyone uses it, WDYT?

thanks

**Comment by elad-bar** [comment]
Added multiple checkbox drop down, now you can just choose,
WDYT?
