### ISSUE TITLE
Failed to store partial message for later processing

### ISSUE THREAD

**Issue by zacksii** [elad-bar/ha-edgeos#92]
Hi there, would you mind taking a look on this issue I receive constantly?
Thanks in advance 

----
Logger: custom_components.edgeos.component.api.websocket
Source: custom_components/edgeos/component/api/websocket.py:101
Integration: Ubiquiti EdgeOS Routers ([documentation](https://github.com/elad-bar/ha-edgeos), [issues](https://github.com/elad-bar/ha-edgeos/issues))
First occurred: 19:03:44 (2 occurrences)
Last logged: 19:07:14

Failed to store partial message for later processing
------

Home Assistant 2023.1.7
Supervisor 2023.01.1
Frontend 20230110.0 - latest

**Comment by elad-bar** [comment]
That's a warning message, when the message being sent from the router is not valid and being dropped, unless you have many of them in short timeframe, you can ignore it

**Comment by zacksii** [comment]
Thanks
