### ISSUE TITLE
sensor.xxxx_last_restart has device class None, state class total_increasing since 2023.2.x

### ISSUE THREAD

**Issue by alvinchen1** [elad-bar/ha-edgeos#94]
Hello! Looks like there are some recent changes where state class, device class and state are stricter.  Since 2023.2.x getting a new 
 Core Log Warning:

Sensor sensor.xxxx_last_restart has device class None, state class total_increasing and unit None thus indicating it has a numeric value; however, it has the non-numeric value: 2023-01-23 19:58:26 (<class 'datetime.datetime'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

Device:

<img width="496" alt="image" src="https://user-images.githubusercontent.com/26409535/216825082-7d85dd51-190f-4b7c-b9ee-6634f8bfeae9.png">

Looks like line 849 in https://github.com/elad-bar/ha-edgeos/blob/master/custom_components/edgeos/component/managers/home_assistant.py

state_class=SensorStateClass.TOTAL_INCREASING

Might need to be dropped?

**Comment by elad-bar** [comment]
released new version with fix for it, [v2.0.25](https://github.com/elad-bar/ha-edgeos/releases/tag/v2.0.25), pls check and let me know if works for you

 thanks

**Comment by alvinchen1** [comment]
Don't see the error anymore.  Thanks!
