### ISSUE TITLE
Entity sensor.edgerouter_interface_XXX_sent_rate is using state class 'total_increasing' which is impossible considering device class ('data_rate') it is using since v2.0.27

### ISSUE THREAD

**Issue by alvinchen1** [elad-bar/ha-edgeos#96]
Howdy, looks like a new one from the change to the sent_rate starting with v2.0.27?

Entity sensor.edgerouter_interface_XXX_sent_rate (<class 'custom_components.edgeos.core.components.sensor.CoreSensor'>) is using state class 'total_increasing' which is impossible considering device class ('data_rate') it is using; expected None or one of 'measurement'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

and
Entity sensor.edgerouter_interface_XXX_sent_rate from integration edgeos has state class total_increasing, but its state is not strictly increasing. Triggered by state 5294.0 (5448.0) with last_updated set to 2023-03-03T10:07:18.977591+00:00. Please report it to the custom integration author.

Thanks as always!

**Comment by elad-bar** [comment]
released v2.0.28 to fix it, pls check and report back

thanks

**Comment by alvinchen1** [comment]
Warning no longer showing up. Thanks!
