### ISSUE TITLE
Long Term Statistics not working:

### ISSUE THREAD

**Issue by Marr0w59** [elad-bar/ha-edgeos#97]
Statistics need to be updated per:  https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

**Comment by elad-bar** [comment]
can you pls provide more details, is it related to #96?

thanks

**Comment by elad-bar** [comment]
released v2.0.28 to fix it, pls check and report back

thanks

**Comment by Marr0w59** [comment]
Pulled latest, still same issue.  If I try to add the last 7 days interface send and receive rates to a statistics card on a dashboard, there is no data displayed.

**Comment by Marr0w59** [comment]
I was just poking around, and I can see the history data on the entity itself? but if I add that entity to statistics graph card it does not display.  Maybe a HA issue, not the integration.
