### ISSUE TITLE
 The unit of this entity changed from 'B/ps' to 'B/s'

### ISSUE THREAD

**Issue by Dude4Linux** [elad-bar/ha-edgeos#99]
**Information Only:**
Apparently the units for  Interface ETH0 Sent & Received Rates were changed in an update sometime after I first installed the Integration.  This results in errors being logged and new values being discarded. The problem can easily be fixed using the Statistics tab on the Developers Tools page.  Just click FIX ISSUE and select "Update the unit of the historic statistic values from 'B/ps' to 'B/s', without converting."

**Comment by elad-bar** [comment]
Was aligned with HA official units

**Comment by elad-bar** [comment]
can that issue get close?

thanks
